#!/usr/bin/env py -3
"""make_html_report.py --out FILE [audit.txt ...] : turn audit .txt files into one HTML page.
Usage: py -3 make_html_report.py --out report.html audits/*.txt
Pure stdlib. Highlights MISSING/FAIL findings. No external deps."""
import sys, argparse, html, io, os

def parse_site(lines, fallback):
    for ln in lines:
        for tok in ln.replace(":", " ").split():
            if tok.startswith("http"):
                return tok.split("/")[2] if "//" in tok else tok
    return fallback

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("inputs", nargs="+")
    a = ap.parse_args()
    cards = []
    for path in a.inputs:
        with io.open(path, encoding="utf-8", errors="replace") as f:
            raw = f.read()
        lines = raw.splitlines()
        site = parse_site(lines[:6], os.path.basename(path).replace(".txt", ""))
        rows = []
        for ln in lines:
            s = ln.strip()
            if not s or s.startswith("===") or s.startswith("#"):
                continue
            flag = ""
            low = s.lower()
            if "missing" in low or "fail" in low or "unavailable" in low:
                flag = ' style="color:#b00020;font-weight:600"'
            elif "present" in low or "ok" in low:
                flag = ' style="color:#0a7d33"'
            rows.append('<li%s>%s</li>' % (flag, html.escape(s)))
        n_missing = sum(1 for ln in lines if "missing" in ln.lower())
        cards.append(
            '<section class="card"><h2>%s</h2><p>%d findings highlighted as gaps</p>'
            '<ul>%s</ul></section>' % (html.escape(site), n_missing, "".join(rows)))
    doc = """<!doctype html><html><head><meta charset="utf-8">
<title>Site Audit Report</title><style>
body{font-family:system-ui,sans-serif;margin:2rem;max-width:60rem}
.card{border:1px solid #ddd;border-radius:8px;padding:1rem 1.25rem;margin-bottom:1rem}
.card h2{margin:0 0 .25rem;font-size:1.1rem}
.card li{margin:.2rem 0;font-size:.9rem;font-family:ui-monospace,monospace}
</style></head><body><h1>Site Audit Report</h1>
<p>Generated by site-audit (3-module chain: core + on-page extras + hardening/crawlability/social).</p>
%s</body></html>""" % "".join(cards)
    with io.open(a.out, "w", encoding="utf-8") as f:
        f.write(doc)
    print("wrote %s (%d cards, %d bytes)" % (a.out, len(cards), len(doc)))

if __name__ == "__main__":
    main()
