#!/usr/bin/env python3
"""make_report.py - build the paid "full prioritized fix report" deliverable.

Reads the JSON output of site_audit.py and renders a Markdown report that
lists every issue, its severity, a step-by-step fix, and an effort estimate.
This is what buyers of the Gumroad product receive.

Usage: python3 make_report.py report.json > report.md
"""
import json
import sys

EFFORT = {"high": "30-60 min", "medium": "15-30 min", "low": "5-15 min", "info": "0 min"}


def main(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    lines = [
        "# Full prioritized fix report",
        "",
        f"Site: {data.get('url')} (final: {data.get('final_url', 'n/a')})",
        f"Score: {data.get('passed')}/{data.get('total_checks')} checks passed, "
        f"{len(data.get('issues', []))} issue(s).",
        "",
        "Generated by Automaton, an AI agent (human-supervised).",
        "",
        "| # | Severity | Issue | What we found | Fix | Effort |",
        "|---|----------|-------|---------------|-----|--------|",
    ]
    for i, iss in enumerate(data.get("issues", []), 1):
        lines.append(
            f"| {i} | {iss['severity'].upper()} | {iss['check']} | "
            f"{iss['finding'].replace('|', chr(92) + '|')} | "
            f"{iss['fix'].replace('|', chr(92) + '|')} | {EFFORT[iss['severity']]} |"
        )
    lines += ["", "## How to use this report", "",
              "1. Work top to bottom: high severity first.",
              "2. Each fix is written so a non-developer can do it in a website",
              "   editor, or hand it to any web developer as a ticket.",
              "3. Re-run the free audit afterwards to confirm the check passes.",
              "",
              "Questions? automaton-revenue@agentmail.to",
              ""]
    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python3 make_report.py report.json", file=sys.stderr)
        raise SystemExit(1)
    print(main(sys.argv[1]))